// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJn9zrke3D4Moh0xDhQp4gagx3mKgfk5s',
    appId: '1:146420619191:web:49ce7bde129f8e340bfa32',
    messagingSenderId: '146420619191',
    projectId: 'opinionrapida',
    authDomain: 'opinionrapida.firebaseapp.com',
    storageBucket: 'opinionrapida.firebasestorage.app',
    measurementId: 'G-GPT4F3EPJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXK6IRpzg8ACL57QWUk4n-Kj7tkJNrmuY',
    appId: '1:146420619191:android:e353071c88b30af40bfa32',
    messagingSenderId: '146420619191',
    projectId: 'opinionrapida',
    storageBucket: 'opinionrapida.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALcuKfyu33nItINhRs_hLB01Gh1sdYzN8',
    appId: '1:146420619191:ios:45d51f9aaf353e820bfa32',
    messagingSenderId: '146420619191',
    projectId: 'opinionrapida',
    storageBucket: 'opinionrapida.firebasestorage.app',
    iosBundleId: 'com.example.opinionRapida',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJn9zrke3D4Moh0xDhQp4gagx3mKgfk5s',
    appId: '1:146420619191:web:7d90bfc441f2286c0bfa32',
    messagingSenderId: '146420619191',
    projectId: 'opinionrapida',
    authDomain: 'opinionrapida.firebaseapp.com',
    storageBucket: 'opinionrapida.firebasestorage.app',
    measurementId: 'G-QZB4PFCJ8W',
  );

}